### ISSUE TITLE
Party.setValue is a confusing API

### ISSUE THREAD

**Issue by bkase** [o1-labs/snarkyjs#277] opened 2022-07-11 20:48 UTC
We should set values in the party structure in a cleaner way

**Comment by mitschabaude** [comment] 2022-07-12 16:14
how about this: we extend the `this.account` fields with `.set()` methods, e.g. `this.account.delegate.set(delegate)`.
we could add new fields for the ones that aren't preconditions, e.g. `this.account.permissions`

**Comment by mitschabaude** [comment] 2022-10-31 19:13
dupe of #186

**Closed by mitschabaude** 2022-10-31 19:13 UTC
