### ISSUE TITLE
this.reducer.getActions returns duplicate actions for the current chain tip 

### ISSUE THREAD

**Issue by garethtdavies** [o1-labs/snarkyjs#804] opened 2023-03-22 01:38 UTC
If there are multiple blocks at the chain tip, `this.reducer.getActions` will return duplicate values for actions. This results in a failure when reducing the actions as below. In this case there were 3 actions and 2 blocks at the chain tip:

```
Failed to derive correct actions hash for B62qkmJvYCoXrCPSx6kSH12KUwyNyfp2PLVrdS2pGxsnHCHpWJtdcTT.
            Derived hash: xkwdExB1EwPceGgXv5CAPm5wxsSFVCsNmnyJs8brLo8k9T7i9S, expected hash: xv5PGcNwLiabhbDcEYMUUsUSqq9A6yYxJWv4oBpPMS8swbUqeu).
            All action hashes derived: [
      {
        "actions": [
          [
            "1"
          ]
        ],
        "hash": "wf7dUpkwY3e8quBYqGn8F47nLJdZGmWPfAZQ4CVB3JtThRjPWD"
      },
      {
        "actions": [
          [
            "1"
          ]
        ],
        "hash": "xrnES4MUSvpgucrfMNEXptfbUva47kXH5z9uRtiLeyTDkjC2Ca"
      },
      {
        "actions": [
          [
            "1"
          ]
        ],
        "hash": "xv5PGcNwLiabhbDcEYMUUsUSqq9A6yYxJWv4oBpPMS8swbUqeu"
      },
      {
        "actions": [
          [
            "1"
          ]
        ],
        "hash": "xzfdTRNrq38qs33Ltj118bNz6vQbkB3qjaorCJ8Hr9wc7YBbse"
      },
      {
        "actions": [
          [
            "1"
          ]
        ],
        "hash": "wXc3yE33tMQAJ7fmV1iQG235zeeesn7Z8ihhE4egVBeBBT7NGX"
      },
      {
        "actions": [
          [
            "1"
          ]
        ],
        "hash": "xkwdExB1EwPceGgXv5CAPm5wxsSFVCsNmnyJs8brLo8k9T7i9S"
      }
    ]
            Please try a different Archive Node API endpoint.
```
While this can be resolved by waiting for an additional block before processing actions, perhaps it would be better to return no actions in this instance rather than duplicate, which is guaranteed to fail.

**Comment by MartinMinkov** [comment] 2023-04-04 23:19
Good news - we've merged a workaround for this issue in https://github.com/o1-labs/snarkyjs/pull/817. The upcoming release of SnarkyJS will include this fix, so I'll be closing this issue.

This workaround follows a similar approach to events and serves as a temporary solution. Once we redeploy the Berkeley network, we'll be able to address the root cause of this issue. 😊

You can track that related issue here: https://github.com/o1-labs/Archive-Node-API/issues/7

**Closed by MartinMinkov** 2023-04-04 23:19 UTC
Labels: ITN-zkApps-E2E-testing, product-eng
